In [1]:
import warnings
# warnings.simplefilter(action='ignore', category=FutureWarning)

import numpy as np
import pandas as pd
from pandas import MultiIndex, Int64Dtype
import matplotlib.pyplot as plt

import xgboost as xgb
from xgboost import XGBRegressor
print("XGB Version:", xgb.__version__)

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.inspection import permutation_importance
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

/tmp/ipykernel_4350/642861182.py:5: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


XGB Version: 2.0.3


In [2]:
df = pd.read_csv("train_and_macro_together.csv")

In [3]:
x = df.drop(columns=['price_doc', 'id'])
y = df['price_doc']

In [4]:
cat_columns_names = df.select_dtypes(include=['category', 'object']).columns.to_list()

In [5]:
codes = {}
for name in cat_columns_names:
    s = set(x[name].unique().tolist())
    codes[name] = dict(zip(s, range(len(s))))
    def c2n(item):
        return codes[name][item]
    x[name] = x[name].apply(c2n)


In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [8]:
model = XGBRegressor(n_estimators = 3000, max_depth = 30, random_state = 42)

In [9]:
model.fit(x_train, y_train)

In [25]:
model.predict(x_train)

array([ 5867443. ,  9500008. ,  3357784.2, ..., 10049983. ,  7450020.5,
       14700035. ], dtype=float32)

In [26]:
y_pred = model.predict(x_test)
y_pred

array([ 9769225. , 11910316. ,  6116741. , ...,  7879013.5,  4326419. ,
        4453328. ], dtype=float32)

In [27]:
model.predict(x_test[0])

array([9769225.], dtype=float32)

In [28]:
mean_absolute_error(y_test, y_pred)

1194307.3946417589